import type { NextPage } from 'next'
import Head from "next/head";
import Script from "next/script";

import Home from "../components/home";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Testing User-Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <Script id="user-way">{`(function(d){var s = d.createElement("script");s.setAttribute("data-account", "zgyErMLytm");s.setAttribute("src", "https://cdn.userway.org/widget.js");(d.body || d.head).appendChild(s);})(document)`}</Script>
    </div>
  );
};

export default HomePage;
